/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsBrandRouteImport } from './routes/brands.$brand'
import { Route as BrandsBrandIndexRouteImport } from './routes/brands.$brand.index'
import { Route as BrandsBrandInsightsRouteImport } from './routes/brands.$brand.insights'
import { Route as BrandsBrandForCompaniesRouteImport } from './routes/brands.$brand.for-companies'
import { Route as BrandsBrandForCandidatesRouteImport } from './routes/brands.$brand.for-candidates'
import { Route as BrandsBrandAboutRouteImport } from './routes/brands.$brand.about'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandRoute = BrandsBrandRouteImport.update({
  id: '/brands/$brand',
  path: '/brands/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIndexRoute = BrandsBrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsBrandRoute,
} as any)
const BrandsBrandInsightsRoute = BrandsBrandInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => BrandsBrandRoute,
} as any)
const BrandsBrandForCompaniesRoute = BrandsBrandForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => BrandsBrandRoute,
} as any)
const BrandsBrandForCandidatesRoute =
  BrandsBrandForCandidatesRouteImport.update({
    id: '/for-candidates',
    path: '/for-candidates',
    getParentRoute: () => BrandsBrandRoute,
  } as any)
const BrandsBrandAboutRoute = BrandsBrandAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BrandsBrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/brands/$brand': typeof BrandsBrandRouteWithChildren
  '/brands/': typeof BrandsIndexRoute
  '/brands/$brand/about': typeof BrandsBrandAboutRoute
  '/brands/$brand/for-candidates': typeof BrandsBrandForCandidatesRoute
  '/brands/$brand/for-companies': typeof BrandsBrandForCompaniesRoute
  '/brands/$brand/insights': typeof BrandsBrandInsightsRoute
  '/brands/$brand/': typeof BrandsBrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/brands': typeof BrandsIndexRoute
  '/brands/$brand/about': typeof BrandsBrandAboutRoute
  '/brands/$brand/for-candidates': typeof BrandsBrandForCandidatesRoute
  '/brands/$brand/for-companies': typeof BrandsBrandForCompaniesRoute
  '/brands/$brand/insights': typeof BrandsBrandInsightsRoute
  '/brands/$brand': typeof BrandsBrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/brands/$brand': typeof BrandsBrandRouteWithChildren
  '/brands/': typeof BrandsIndexRoute
  '/brands/$brand/about': typeof BrandsBrandAboutRoute
  '/brands/$brand/for-candidates': typeof BrandsBrandForCandidatesRoute
  '/brands/$brand/for-companies': typeof BrandsBrandForCompaniesRoute
  '/brands/$brand/insights': typeof BrandsBrandInsightsRoute
  '/brands/$brand/': typeof BrandsBrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/sitemap.xml'
    | '/team'
    | '/brands/$brand'
    | '/brands/'
    | '/brands/$brand/about'
    | '/brands/$brand/for-candidates'
    | '/brands/$brand/for-companies'
    | '/brands/$brand/insights'
    | '/brands/$brand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/sitemap.xml'
    | '/team'
    | '/brands'
    | '/brands/$brand/about'
    | '/brands/$brand/for-candidates'
    | '/brands/$brand/for-companies'
    | '/brands/$brand/insights'
    | '/brands/$brand'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/sitemap.xml'
    | '/team'
    | '/brands/$brand'
    | '/brands/'
    | '/brands/$brand/about'
    | '/brands/$brand/for-candidates'
    | '/brands/$brand/for-companies'
    | '/brands/$brand/insights'
    | '/brands/$brand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  BrandsBrandRoute: typeof BrandsBrandRouteWithChildren
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brand': {
      id: '/brands/$brand'
      path: '/brands/$brand'
      fullPath: '/brands/$brand'
      preLoaderRoute: typeof BrandsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brand/': {
      id: '/brands/$brand/'
      path: '/'
      fullPath: '/brands/$brand/'
      preLoaderRoute: typeof BrandsBrandIndexRouteImport
      parentRoute: typeof BrandsBrandRoute
    }
    '/brands/$brand/insights': {
      id: '/brands/$brand/insights'
      path: '/insights'
      fullPath: '/brands/$brand/insights'
      preLoaderRoute: typeof BrandsBrandInsightsRouteImport
      parentRoute: typeof BrandsBrandRoute
    }
    '/brands/$brand/for-companies': {
      id: '/brands/$brand/for-companies'
      path: '/for-companies'
      fullPath: '/brands/$brand/for-companies'
      preLoaderRoute: typeof BrandsBrandForCompaniesRouteImport
      parentRoute: typeof BrandsBrandRoute
    }
    '/brands/$brand/for-candidates': {
      id: '/brands/$brand/for-candidates'
      path: '/for-candidates'
      fullPath: '/brands/$brand/for-candidates'
      preLoaderRoute: typeof BrandsBrandForCandidatesRouteImport
      parentRoute: typeof BrandsBrandRoute
    }
    '/brands/$brand/about': {
      id: '/brands/$brand/about'
      path: '/about'
      fullPath: '/brands/$brand/about'
      preLoaderRoute: typeof BrandsBrandAboutRouteImport
      parentRoute: typeof BrandsBrandRoute
    }
  }
}

interface BrandsBrandRouteChildren {
  BrandsBrandAboutRoute: typeof BrandsBrandAboutRoute
  BrandsBrandForCandidatesRoute: typeof BrandsBrandForCandidatesRoute
  BrandsBrandForCompaniesRoute: typeof BrandsBrandForCompaniesRoute
  BrandsBrandInsightsRoute: typeof BrandsBrandInsightsRoute
  BrandsBrandIndexRoute: typeof BrandsBrandIndexRoute
}

const BrandsBrandRouteChildren: BrandsBrandRouteChildren = {
  BrandsBrandAboutRoute: BrandsBrandAboutRoute,
  BrandsBrandForCandidatesRoute: BrandsBrandForCandidatesRoute,
  BrandsBrandForCompaniesRoute: BrandsBrandForCompaniesRoute,
  BrandsBrandInsightsRoute: BrandsBrandInsightsRoute,
  BrandsBrandIndexRoute: BrandsBrandIndexRoute,
}

const BrandsBrandRouteWithChildren = BrandsBrandRoute._addFileChildren(
  BrandsBrandRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  BrandsBrandRoute: BrandsBrandRouteWithChildren,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
